/*
 * File: app/store/BusinessStore.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.BusinessStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.Business'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            storeId: 'MyJsonStore',
            model: 'MyApp.model.Business',
            proxy: {
                type: 'ajax',
                api: {
                    read: 'http://localhost:8888/data/yelp/yelp_training_set_business.json',
                    write: 'http://localhost:8888/yelp/data/business/update'
                },
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});